#!/bin/sh

rsync -avn --exclude '.cache' --exclude '.thumbnails' --exclude '*.tmp' --exclude '~.*' \
   --exclude 'icons.screen0-*' \
   --exclude 'Schreibtisch' --exclude 'dt-*' \
   --exclude '.ICEauthority' --exclude '.Xauthority' --exclude '.xsession-err*' \
   /home/nwboxuser smb01:/export/files
